use_frameworks!
target "IBMMobileFirstPlatformFoundationLiveUpdate" do
	pod 'IBMMobileFirstPlatformFoundation', '~> 8.0'
end

target "IBMMobileFirstPlatformFoundationLiveUpdateTests" do
        pod 'IBMMobileFirstPlatformFoundation', '~> 8.0'
end
