./build.sh ConfigurationServiceSDK
cp -vr ./universal/Debug/ConfigurationServiceSDK.framework ../ConfigurationServiceSDKTest/Pods/IBMMobileFirstPlatformFoundationConfigurationService/IBMMobileFirstPlatformFoundationConfigurationService/Frameworks
