./build.sh ConfigurationServiceSDK
cp -vr ./universal/Release/ConfigurationServiceSDK.framework ../ConfigurationServiceSDKTest/Pods/IBMMobileFirstPlatformFoundationConfigurationService/IBMMobileFirstPlatformFoundationConfigurationService/Frameworks
